### ISSUE TITLE
Implement starting screen with instructions as different scene

### ISSUE THREAD

**Issue by karen-ly** [interaction-lab/MoveToCode#28]
- [ ] Have user holds their device at eye level and confirm that they are in the position they want to be in
- [ ] Tell user to direct phone horizontally for the best experience
- [ ] Option to rotate angularly (360)/turn the blocks around
- [ ] Instructions about different touches (like pinching with two fingers to rotate, etc.)

**Comment by tgroechel** [comment]
This has been removed for tutorial, closing
