### ISSUE TITLE
Allow user to re-orient themselves

### ISSUE THREAD

**Issue by ipekgoktan** [interaction-lab/MoveToCode#30]
It is difficult to view the game all at once and the user can't adjust where the scene is placed / how big everything is for their own comfort. Entire console game is “fixed” at the physical location that you opened your phone at, it shifts to your desired angle occasionally but it isn't very user friendly.

Possible solution is to add an adjustable dial or programming in a feature where users can zoom in and out.

Another solution is automating the relocating.  A reset button that centers the scene based on your current view could work.

Another solution is to have a scroll/scale to adjust aspect ratio.

**Comment by tgroechel** [comment]
Address this in #73 , closing to clean up issues
