### ISSUE TITLE
Logging Manager C# Property

### ISSUE THREAD

**Issue by karen-ly** [interaction-lab/MoveToCode#47]
I should remember to turn this into a C# property that has an intialization/getter. No need to right now but for future reference: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties

_Originally posted by @tgroechel in https://github.com/interaction-lab/MoveToCode/pull/46#discussion_r591634156_

**Comment by tgroechel** [comment]
Hacky fix in there so no need for this anymore
