### ISSUE TITLE
Variable Memory Bug with Updating Values

### ISSUE THREAD

**Issue by tgroechel** [interaction-lab/MoveToCode#59]
Description ripped from Slack:

Possible bug with the While loop when trying to do a program using variables in memory where we set the var1 to 5 and var2 to 10. In the while block, we put the print(var1) and then incremented the var1, but the console does not print out the var1 value at all, but the memory console does show the stored values for var1 and var2.

**Comment by karen-ly** [comment]
The bug no longer exists!

**Comment by tgroechel** [comment]
Baller, closing!
