### ISSUE TITLE
Feature to enlarge and decrease size of blocks with pinching does not work on mobile

### ISSUE THREAD

**Issue by karen-ly** [interaction-lab/MoveToCode#62]
Need to retest on mobile build

**Comment by karen-ly** [comment]
@ipekgoktan

**Comment by tgroechel** [comment]
@karen-ly is this a desired behavior? An issue with this is that block snapping is super fragile/assumes a lot about block sizing.

I think possibly a desired behavior is to scale everything up/down via a slider. The scale you can change to scale everything would be `Managers`. This would scale all menus as well.

**Comment by karen-ly** [comment]
Oh yeah that sounds like a good alternative (I can prob look into that down the road)! I think Ipek made a feature that allows you to resize the block menu by pinching earlier this semester, but it only works on the computer version of Unity and not the mobile version

**Comment by tgroechel** [comment]
Ok let me know if we should meet or anything about this before usability study (if you want this feature included)

**Comment by tgroechel** [comment]
Looks like `CodeBlockMenuManager` deliberately turns this off when it is enabled, easy to remove if you want, issue is the CodeBlocks won't follow standardized sizing

**Comment by tgroechel** [comment]
I think we should standardize size now or instead address it using #30
