### ISSUE TITLE
iOS Deployment Preparation

### ISSUE THREAD

**Issue by karen-ly** [interaction-lab/MoveToCode#70]
Preparing for iOS Deployment:
1. Sign up for Apple Developer Program -> Tom
2. App Privacy Policy (public URL link to a privacy policy) -> Karen and Tom
3. Screenshots Specifications -> Karen
4. App logo -> Ipek?

Other (TestFlight):
- still need to upload one beta build of app to App Store Connect and testers will download TestFlight App instead which will contain our app (we can invite them through email or send a public link)
- https://www.raywenderlich.com/10868372-testflight-tutorial-ios-beta-testing 
1. Sign up for Apple Developer Program
2. Go to App Store Connect and create a new app
3. Make Archive from Xcode

**Comment by tgroechel** [comment]
Done, works with testflight
