### ISSUE TITLE
Control Kuri with code blocks

### ISSUE THREAD

**Issue by karen-ly** [interaction-lab/MoveToCode#77]
- [x]  Ability to customize Kuri's movement
  - [x] move forward/backward
  - [x] turn right/let 
- [x] Ability to customize Kuri appearance 
  - [x] add color control blocks
- [x] Repeater blocks

**Comment by tgroechel** [comment]
Checkout the [robot-codeblocks](https://github.com/interaction-lab/MoveToCode/tree/robot-codeblocks) branch when you get the chance too, I have some rudimentary code blocks (move forward/back) that control the physical Kuri

I like the idea about customizing appearance

**Comment by tgroechel** [comment]
<img width="582" alt="Screen Shot 2021-12-27 at 2 49 52 PM" src="https://user-images.githubusercontent.com/15292506/147502929-45242940-d5d1-46a1-aab2-a539dee0a086.png">
Codeblock diagram

**Comment by tgroechel** [comment]
<img width="972" alt="Screen Shot 2021-12-28 at 1 01 24 PM" src="https://user-images.githubusercontent.com/15292506/147594095-9cffa37d-afc0-4deb-a179-cedb4ad63ddc.png">
Kuri set up diagram
