### ISSUE TITLE
Implement shadows that project on real world surfaces

### ISSUE THREAD

**Issue by ipekgoktan** [interaction-lab/MoveToCode#81]
- [x] generate shadows that project on spatial mesh
- [x] Add shadow components to all 3D objects in M2C mobile
- [x]  integrate mrtk spatial mesh to android and ios builds
- [x] generate shadows on mobile build

- mac download for CUDA: [https://developer.nvidia.com/nvidia-cuda-toolkit-11_1_0-developer-tools-mac-hosts](url)

- alternate shadow api (costs 5$): https://assetstore.unity.com/packages/templates/packs/ar-shadow-ar-foundation-arkit-arcore-augmented-reality-ar-shader-189753?aid=1100lGft&utm_campaign=unity_affiliate&utm_medium=affiliate&utm_source=partnerize-linkmaker
- https://makaka.org/unity-assets/ar-shadow
- - https://github.com/jonas-johansson/ARCoreUtils
- https://docs.unity3d.com/Manual/class-Projector.html
- https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/spatial-object-mesh-observer?view=mrtkunity-2021-05
- https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/using-ar-foundation?view=mrtkunity-2021-05

**Comment by tgroechel** [comment]
Done
