### ISSUE TITLE
Add a new button that allows user to move onto the next challenge for tutorial

### ISSUE THREAD

**Issue by karen-ly** [interaction-lab/MoveToCode#85]
- currently, you have to press single step to move onto the next challenge which might not be intuitive
- could also implement where it automatically goes onto the next challenge after user finishes and didn't click anything (after 15-30 seconds) move on?

**Comment by tgroechel** [comment]
I believe this is done, closing, please double check @karen-ly

**Comment by karen-ly** [comment]
Didn't see this until now - but yes, it is done!
